server.port=8080
spring.application.name=analyzer

### Postgres Database configurations
spring.datasource.url=jdbc:postgresql://localhost:5432/cashelm
spring.datasource.username=postgres
spring.datasource.password=password

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB
